name: m
favicon: null
layout_spectrum: 0.6046219996642321
typography_spectrum: 0.24581903335638344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7420302818063647
  lightness: 0.9936563419178128
  saturation: 0.2161583777051419
  rhythmicContrast: 0.0957589210011065
purpose: []
