name: m
favicon: null
layout_spectrum: 0.72489
typography_spectrum: 0.24581903335638344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1623'
    - '#c2b0ac'
    - '#86716e'
    - '#433238'
    - '#eeeaeb'
  brandStrength: 0.7420302818063647
  lightness: 0.9375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
